# Generated by Django 4.1.6 on 2023-02-08 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_alter_message_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
    ]
