# Generated by Django 4.1.6 on 2023-02-08 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
