# Generated by Django 4.1.6 on 2023-02-09 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_room_message_r_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='r_id',
            new_name='room_id',
        ),
    ]
