# Generated by Django 4.1.6 on 2023-02-09 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_rename_r_id_message_room_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room_id',
        ),
    ]
