# Generated by Django 4.1.6 on 2023-02-09 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_remove_message_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='messaging.room'),
        ),
    ]
